// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlbmwDUmXZdTPgCHhxUXV1QB6otFEZME',
    appId: '1:488321043548:web:94bb0e3e7ec3750679ea99',
    messagingSenderId: '488321043548',
    projectId: 'techbot-f1402',
    authDomain: 'techbot-f1402.firebaseapp.com',
    storageBucket: 'techbot-f1402.appspot.com',
    measurementId: 'G-7S0E6FMWX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2uLKStU-r2_Bghq29x8v3SYs7ims_No0',
    appId: '1:488321043548:android:bf654156403a70dd79ea99',
    messagingSenderId: '488321043548',
    projectId: 'techbot-f1402',
    storageBucket: 'techbot-f1402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJB1YBmdzj4KkSjez6REOqvYRyrfR7FI',
    appId: '1:488321043548:ios:13e1f562c63a6f4d79ea99',
    messagingSenderId: '488321043548',
    projectId: 'techbot-f1402',
    storageBucket: 'techbot-f1402.appspot.com',
    iosBundleId: 'com.example.techbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJB1YBmdzj4KkSjez6REOqvYRyrfR7FI',
    appId: '1:488321043548:ios:13e1f562c63a6f4d79ea99',
    messagingSenderId: '488321043548',
    projectId: 'techbot-f1402',
    storageBucket: 'techbot-f1402.appspot.com',
    iosBundleId: 'com.example.techbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSlbmwDUmXZdTPgCHhxUXV1QB6otFEZME',
    appId: '1:488321043548:web:db000dca2e8e46e879ea99',
    messagingSenderId: '488321043548',
    projectId: 'techbot-f1402',
    authDomain: 'techbot-f1402.firebaseapp.com',
    storageBucket: 'techbot-f1402.appspot.com',
    measurementId: 'G-5YMGVHZVDQ',
  );
}
